#!/bin/bash
module unload python

if [[ $(type -t conda) == function ]]; then
    conda deactivate # Necessary when rerunning this to not cause problems with ROOT.
fi

#Below loads the appropriate conda version
module load python

#Below will set the conda setting that adds an ugly environment name extension to the command prompt.
conda config --set changeps1 False

#Below will put you in a conda environment with ROOT 6.22 loaded.
source activate root-6.22.02
echo "ROOT and Python 3 Loaded"
